qt/dbus/qdbus.h usr/include/dbus-1.0/dbus/qdbus.h
debian/tmp/usr/include/dbus-1.0/dbus/qdbusabstractadaptor.h
debian/tmp/usr/include/dbus-1.0/dbus/qdbusabstractinterface.h
debian/tmp/usr/include/dbus-1.0/dbus/qdbusbus.h
debian/tmp/usr/include/dbus-1.0/dbus/qdbusconnection.h
debian/tmp/usr/include/dbus-1.0/dbus/qdbuserror.h
debian/tmp/usr/include/dbus-1.0/dbus/qdbusinterface.h
debian/tmp/usr/include/dbus-1.0/dbus/qdbusmacros.h
debian/tmp/usr/include/dbus-1.0/dbus/qdbusmessage.h
debian/tmp/usr/include/dbus-1.0/dbus/qdbusreply.h
debian/tmp/usr/include/dbus-1.0/dbus/qdbusserver.h
debian/tmp/usr/include/dbus-1.0/dbus/qdbustypehelper_p.h
debian/tmp/usr/include/dbus-1.0/dbus/qdbusutil.h
debian/tmp/usr/lib/pkgconfig/dbus-qt4-1.pc
debian/tmp/usr/lib/libdbus-qt4*.a
debian/tmp/usr/lib/libdbus-qt4*.so
debian/tmp/usr/bin/dbuscpp2xml
debian/tmp/usr/bin/dbusidl2cpp
